In [1]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [2]:
print(df.loc[[0, 4, 7, 8]])

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [5]:
print(df.iloc[3:8])

print(df.iloc[4:9, 2:5])

print(df.iloc[:, 1:4])

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No
  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [7]:
import pandas as pd

df = pd.read_csv("Iris.csv")

print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
import pandas as pd

df = pd.read_csv("Iris.csv")

df = df.drop(index=4)

df = df.drop(df.columns[3], axis=1)

print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [9]:
df = pd.read_csv("employees.csv")

print(df.shape)

(5, 10)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [11]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [12]:
print(df.head(5))
print(df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [13]:
print("Average Salary:", df["Salary"].mean())
print("Total Bonus:", df["Bonus"].sum())
print("Youngest Age:", df["Age"].min())
print("Highest Rating:", df["Rating"].max())

Average Salary: 60000.0
Total Bonus: 27500
Youngest Age: 28
Highest Rating: 4.7

In [14]:
df = df.sort_values(by="Salary", ascending=False)

print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [15]:
df["Performance"] = df["Rating"].apply(
    lambda x: "Excellent" if x >= 4.5
    else "Good" if x >= 4.0
    else "Average"
)

print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating Performance
1   2017-07-19    Male   7000     4.0        Good
2   2013-06-01    Male   6000     3.8     Average
4   2010-11-25    Male   5000     3.5     Average
3   2021-02-10  Female   4500     4.7   Excellent
0   2020-03-15  Female   5000     4.5   Excellent

In [16]:
df.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [17]:
df.rename(columns={"Employee_ID": "ID"}, inplace=True)

In [18]:
df[df["Years_of_Experience"] > 5]
df[df["Department"] == "IT"]
df[(df["Years_of_Experience"] > 5) & (df["Department"] == "IT")]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [21]:
df["Tax"] = df["Salary"] * 0.10
print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
3  104    Diana  Marketing   28   55000                    3   2021-02-10
0  101    Alice         HR   29   50000                    4   2020-03-15

   Gender  Bonus  Rating Performance     Tax
1    Male   7000     4.0        Good  7000.0
2    Male   6000     3.8     Average  6500.0
4    Male   5000     3.5     Average  6000.0
3  Female   4500     4.7   Excellent  5500.0
0  Female   5000     4.5   Excellent  5000.0

In [20]:
df.to_csv("modified_employees.csv", index=False)